
# გამოიყენეთ ptint-ცვლადი 20-ჯერ.
print=("tamari")
print=("tamari")
print=("tamari")
print=("tamari")
print=("tamari")
print=("tamari")
print=("tamari")
print=("tamari")
print=("tamari")
print=("tamari")
print=("tamari")
print=("tamari")
print=("tamari")
print=("tamari")
print=("tamari")
print=("tamari")
print=("tamari")
print=("tamari")
print=("tamari")
print=("tamari")
print=("tamari")

